
CREATE TABLE KOSPI(
    DATES       	VARCHAR2(8),
    PERSONAL    	NUMBER,
    FOREIGNER    	NUMBER,
    INSTITUTIONS    NUMBER,
    FI_INVESTMENT   NUMBER,
    INSURANCE    	NUMBER,
    EQUITY    		NUMBER,
    BANK    		NUMBER,
    ETC_F    		NUMBER,
    PENSION_FUND    NUMBER,
    ETC_C    		NUMBER
);