
CREATE TABLE KOSPI(
    DATES       VARCHAR2(8),
    PERSONAL    NUMBER,
    INSTITUTIONS    NUMBER,
    FOREIGNER    NUMBER,
    FI_INVESTMENT    NUMBER,
    INSURANCE    NUMBER,
    EQUITY    NUMBER,
    ETC    NUMBER,
    BANK    NUMBER,
    PENSION_FUND    NUMBER
);